import fs from "fs"
import path from "path"
import matter from "gray-matter"
import Head from 'next/head'
import Post from "../components/Post"
import Header from "../components/Header"
import { sortByDate } from "../utils"

export default function Home({ posts }) {
    return (
        <section className="blog-index">
            <Head>
                <title>Blogg</title>
                <meta name="description" content="Generated by create next app" />
                <meta name="viewport" content="width=device-width, initial-scale=1" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <Header textColor="#050505" />
            <div className="spacer"></div>
            <h2 className="wrapper">Blog index</h2>
            <div className="posts">
                {posts.map((post, index) => (

                    <Post key={index} post={post} />

                )
                )}

            </div>
            <main>
            </main>
        </section>
    )
}

export async function getStaticProps() {
    // Get files from the posts dir
    const files = fs.readdirSync(path.join("posts"))

    // Get slug and frontmatter from posts
    const posts = files.map(filename => {
        //Create slug
        const slug = filename.replace(".md", "")
        // Get frontmatter
        const markdownWithMeta = fs.readFileSync(path.join("posts", filename), "utf-8"
        )

        const { data: frontmatter } = matter(markdownWithMeta)

        return {
            slug,
            frontmatter
        }
    }
    )

    return {
        props: {
            posts: posts.sort(sortByDate),
        },
    }
}